### ISSUE TITLE
Feature 14: User can unfollow a profile

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can unfollow a profile.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user is following a profile, they have the option to unfollow by simply clicking the same button. Text will change back to 'follow.'

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="296" alt="Screen Shot 2022-04-27 at 3 39 47 PM" src="https://user-images.githubusercontent.com/87846307/165642961-c3a3692c-8cc8-4477-b1d8-6ad96a26129c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to insert followers

### ☁️ Server

- [x] Update `server/index.js` to have 'DELETE' route in followers table based on userId
- [x] Test 'DELETE' with HTTPie
- [x] Update `server/index.js` to have 'isFollowing' column in api/user route
- [x] Update `server/index.js` to have postCount, followingCount, and followerCount column in api/user route
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Profile component to fetch 'DELETE' on 'unfollow' clicks
- [x] Update Profile component to have followerCount state change based on follow/unfollow clicks

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
