### ISSUE TITLE
Bug: User can't delete post if there are comments

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#36]
#### Desired Behavior

> ##### The app should ...

The app should always delete a post if user clicks confirm button.

#### Actual Behavior

> ##### The app does this instead ...

Instead, the app keeps modal delete modal open and throws an error in the console if the post has a comment.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

To trigger the bug, you must:
1. Create a post
2. Comment on it
3. Edit the post
4. Confirm deletion of post

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Add nested query to delete comments in delete route for posts in server/index.js
- [x] In delete route for posts, change to 'res.sendStatus(204)'
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
