### ISSUE TITLE
Bug: Like icon doesn't stayed filled if user refreshes the page

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#38]
#### Desired Behavior

> ##### The app should ...

The app should load posts with a filled heart icon if the user previously liked the post.

#### Actual Behavior

> ##### The app does this instead ...

Instead, the app always loads posts with an unfilled heart icon regardless if the user previously liked the post.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

To trigger the bug:
1. Like a post
2. Refresh the page

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Move GET routes for retrieving posts below authorizationMiddleware
- [x] Add req.user to both GET routes for posts
- [x] Add token header to Post and Home component's fetch request for posts
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
