### ISSUE TITLE
Bug: User can press 'share' multiple times

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#40]
#### Desired Behavior

> ##### The app should ...

The app should only share the post once and change routes to home screen

#### Actual Behavior

> ##### The app does this instead ...

Instead, if the user presses the 'share' button more than once then it causes duplicate posts, console errors, and disables view swap.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

To trigger the bug:
1. Click add new post
2. Fill out form
3. Press 'share' more than once

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Add disabled state to render form with disabled attribute in PostForm component
- [x] Set disabled state to true on form submits
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
