### ISSUE TITLE
Bug: User can follow their own profile

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#42]
#### Desired Behavior

> ##### The app should ...

The app should not render the follow/unfollow button when viewing own profile.

#### Actual Behavior

> ##### The app does this instead ...

Instead, the app renders follow/unfollow button for every profile which gives users ability to follow themselves.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...
To trigger the bug:
1. View your profile
2. Click follow/unfollow button

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] In Profile component, add conditional to render follow button only if it's not current user
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
