### ISSUE TITLE
User Sign Up Form Polish

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#46]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [ ] Add form validation
    - [ ] Add full name input
    - [ ] Add confirm password input
    - [ ] Password must be at least 8 characters and maximum of 16 characters
