### ISSUE TITLE
Refactor: Change components folder into functional components

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#47]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Refactor auth-form.jsx
- [x] Refactor comment.jsx
- [x] Refactor dropdown-menu.jsx
- [x] Refactor grid-history.jsx
- [x] Refactor modal.jsx
- [x] Refactor navbar.jsx
- [x] Refactor post-history.jsx
- [x] Refactor post.jsx
- [x] Refactor redirect.jsx
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
