### ISSUE TITLE
Refactor: Pages Folder into Functional Components

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#49]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Refactor auth.jsx
- [x] Refactor home.jsx
- [x] Refactor post-form.jsx
- [x] Refactor profile.jsx
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
