### ISSUE TITLE
Refactor: App and SVG assets folder into functional components

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#51]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Refactor app.jsx
- [x] Refactor camera-icon.jsx
- [x] Refactor chevron-down-icon.jsx
- [x] Refactor comment-icon.jsx
- [x] Refactor delete-icon.jsx
- [x] Refactor grid-icon.jsx
- [x] Refactor heart-icon-filled.jsx
- [x] Refactor heart-icon.jsx
- [x] Refactor list-icon.jsx
- [x] Refactor menu-icon.jsx
- [x] Refactor pen-icon.jsx
- [x] Refactor plus-icon.jsx
- [x] Refactor xmark-icon.jsx
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
