### ISSUE TITLE
Feature 15: User can search for posts based on username

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#53]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search and filter the posts based on the username they enter in the search bar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user clicks the search bar/keyword, it will focus the input and as the user presses a key the posts are rendered based on the search word.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create SearchBar component which receives 'posts' props
- [x] Import SearchBar in components and ensure it has access to posts state from Home
- [x] Create new SVG file to export search icon
- [x] Add event listener onClick so that 'Search' becomes a search bar
- [x] Add handle change to search input field and set state
- [x] Use filter() on posts state to match user query with username in SearchBar

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
