### ISSUE TITLE
Bug: User can't upload image with their post

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#55]
#### Desired Behavior

> ##### The app should ...

Allow user to upload an image when the plus icon is clicked.

#### Actual Behavior

> ##### The app does this instead ...

Does nothing and the user receives no feedback.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Click add post in the navbar
2. Attempt to add an image

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] Check whether the icon is receiving clicks

- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.

**Comment by alexei-dayrit** [comment]
Can't replicate issue, must've been a browser related bug
