### ISSUE TITLE
Bug: posts aren't always shown when clicking on a profile

### ISSUE THREAD

**Issue by alexei-dayrit** [alexei-dayrit/foodies#56]
#### Desired Behavior

> ##### The app should ...

Populate with info based on the profile selected

#### Actual Behavior

> ##### The app does this instead ...

Sometimes populates with info, but more often doesn't display the posts of the current profile.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

1. Click a profile
2. Constantly refresh until posts appear

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Change all state updates into function version
- [x] Verify posts are loaded on component mount
- [x] Make fetch function into separate component
- [x] Import fetch component into Profile component
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
